###############################################################
#
#   Makefile for project07
#
# Students:
# Yahel Yedidya, ID 204365357, yahel.yedidya@mail.huji.ac.il
# Gal Toledano, ID 204631295, gal.toledano@mail.huji.ac.il
##############################################################

all:
	chmod a+x ./JackAnalyzer